version: '2'

services:
  zk:
    image: garland/zookeeper
    ports: 
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment: 
      - SERVER_ID=1
      - ADDITIONAL_ZOOKEEPER_1=server.1=zk:2888:3888

  mesos:
    image: garland/mesosphere-docker-mesos-master
    ports: 
      - 5050:5050
    depends_on: 
      - zk
    environment: 
      - MESOS_HOSTNAME=mesos
      - MESOS_ZK=zk://zk:2181/mesos
      - MESOS_PORT=5050
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
      - MESOS_WORK_DIR=/var/lib/mesos

  mesos_slave:
    image: garland/mesosphere-docker-mesos-master:latest
    entrypoint: mesos-slave
    depends_on: 
      - zk
    environment: 
      - MESOS_MASTER=zk://zk:2181/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_LOGGING_LEVEL=INFO      

  marathon:
    image: garland/mesosphere-docker-marathon
    ports: 
      - 8080:8080
    entrypoint: "/opt/marathon/bin/start --master zk://mesos:2181/mesos --zk zk://zk:2181/marathon"
    depends_on: 
      - mesos
      - zk

